kind: CronJob
apiVersion: batch/v1
metadata:
  name: nrs-query-automation-cron
  namespace: c2b678-prod
spec:
  schedule: 0 4 * * *
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: nrs-query-automation
              image: >-
                image-registry.openshift-image-registry.svc:5000/c2b678-prod/nrs-query-automation@sha256:bb8370cb1146e5e38788c5dca76f145ceee93484b295006a1cc895053fcd4b64
              env:
                - name: apikey
                  valueFrom:
                    secretKeyRef:
                      name: nrs-query-automation
                      key: apikey
                - name: objkey
                  valueFrom:
                    secretKeyRef:
                      name: nrs-query-automation
                      key: objkey
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 600
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
