kind: Deployment
apiVersion: apps/v1
metadata:
  name: nrs-query-automation
  namespace: c2b678-prod
  labels:
    app: nrs-query-automation
    app.kubernetes.io/component: nrs-query-automation
    app.kubernetes.io/instance: nrs-query-automation
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: nrs-query-automation
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: nrs-query-automation
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: nrs-query-automation
          image: >-
            image-registry.openshift-image-registry.svc:5000/c2b678-prod/nrs-query-automation@sha256:a05bf4e6ff6f491f2defe3fa67466368f1ca6f52dd5aebe171e0d91e4e4fa2c0
          env:
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: nrs-query-automation
                  key: apikey
            - name: objkey
              valueFrom:
                secretKeyRef:
                  name: nrs-query-automation
                  key: objkey
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
