kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"nrs-query-automation:latest","namespace":"c2b678-prod"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nrs-query-automation\")].image","pause":"true"}]
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '7240363789'
  name: nrs-query-automation
  uid: 99ac3274-08e7-421e-88db-8255a6203113
  creationTimestamp: '2023-07-28T23:30:29Z'
  generation: 6
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: apps/v1
      time: '2023-07-28T23:30:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"nrs-query-automation"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-07-28T23:30:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"nrs-query-automation"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-07-28T23:56:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
      subresource: status
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-07-29T01:11:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:image.openshift.io/triggers': {}
        'f:spec':
          'f:strategy':
            'f:type': {}
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"nrs-query-automation"}':
                  'f:env':
                    .: {}
                    'k:{"name":"apikey"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"objkey"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
              'f:terminationGracePeriodSeconds': {}
  namespace: c2b678-prod
  labels:
    app: nrs-query-automation
    app.kubernetes.io/component: nrs-query-automation
    app.kubernetes.io/instance: nrs-query-automation
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: nrs-query-automation
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: nrs-query-automation
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: nrs-query-automation
          image: >-
            image-registry.openshift-image-registry.svc:5000/c2b678-prod/nrs-query-automation@sha256:a05bf4e6ff6f491f2defe3fa67466368f1ca6f52dd5aebe171e0d91e4e4fa2c0
          env:
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: nrs-query-automation
                  key: apikey
            - name: objkey
              valueFrom:
                secretKeyRef:
                  name: nrs-query-automation
                  key: objkey
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-07-28T23:37:29Z'
      lastTransitionTime: '2023-07-28T23:30:29Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "nrs-query-automation-744c6ddf5c" has successfully
        progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-07-28T23:56:41Z'
      lastTransitionTime: '2023-07-28T23:56:41Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
